eventos_homepage:
    pattern:  /
    defaults: { _controller: EventosBundle:eventos:index }
usuario_crear:
    pattern:  /usuario/crear
    defaults: { _controller: EventosBundle:eventos:crear }
usuario_mostrartodo:
    pattern:  /usuario/mostrar_todo
    defaults: { _controller: EventosBundle:eventos:mostrarTodo }
usuario_opcion:
    pattern:  /usuario/opciones/{opcion}
    defaults: { _controller: EventosBundle:eventos:opcion }
usuario_opcion_delet:
    pattern:  /usuario/opciones/eliminar/{id}
    defaults: { _controller: EventosBundle:eventos:opcion_delet }
usuario_opcion_update:
    pattern:  /usuario/opciones/modificar/{id}
    defaults: { _controller: EventosBundle:eventos:opcion_update }
distros_crear:
    pattern:  /distros/crear
    defaults: { _controller: EventosBundle:eventos:distros_crear }